server:
  servlet:
    port: 3000
    contextPath: /api

spring:
  application:
    name: reddit-api

  datasource:
    url: jdbc:postgresql://localhost:5432/reddit
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          user_jdbc_metadata_default: false
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect